<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-19T16:14:04 IST" name="Default suite" finished-at="2021-01-19T16:14:09 IST" duration-ms="4727">
    <groups>
    </groups>
    <test started-at="2021-01-19T16:14:04 IST" name="Default test" finished-at="2021-01-19T16:14:09 IST" duration-ms="4727">
      <class name="com.hkw.WeatherInfoTestNew">
        <test-method signature="GetWeatherDetails()[pri:0, instance:com.hkw.WeatherInfoTestNew@7671cb68]" started-at="2021-01-19T16:14:04 IST" name="GetWeatherDetails" finished-at="2021-01-19T16:14:07 IST" duration-ms="2808" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetWeatherDetails -->
        <test-method signature="testGetListOfUsers()[pri:0, instance:com.hkw.WeatherInfoTestNew@7671cb68]" started-at="2021-01-19T16:14:07 IST" name="testGetListOfUsers" finished-at="2021-01-19T16:14:09 IST" duration-ms="1860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetListOfUsers -->
        <test-method is-config="true" signature="testComponents()[pri:0, instance:com.hkw.WeatherInfoTestNew@7671cb68]" started-at="2021-01-19T16:14:09 IST" name="testComponents" finished-at="2021-01-19T16:14:09 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NegativeArraySizeException">
            <message>
              <![CDATA[-10]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NegativeArraySizeException: -10
at com.hkw.WeatherInfoTestNew.testComponents(WeatherInfoTestNew.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.afterRun(TestRunner.java:847)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NegativeArraySizeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testComponents -->
      </class> <!-- com.hkw.WeatherInfoTestNew -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
